Ultimate_Tic_Tac_Toe_Assembly: Ultimate_Tic_Tac_Toe_Assembly.s
	gcc -no-pie -o Ultimate_Tic_Tac_Toe_Assembly Ultimate_Tic_Tac_Toe_Assembly.s
run: Ultimate_Tic_Tac_Toe_Assembly
	./Ultimate_Tic_Tac_Toe_Assembly
